config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  resources :welcome, only: [:index]

  resources :users, except: [:index]

  resources :houses, except: [:index] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, except: [:index, :new, :create]
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :house
  belongs_to :user

  validates :room, presence: true, uniqueness: { scope: :house_id }
  validates :rating, numericality: { only_integer: true }, inclusion: { in: -1..1 }
  validates :pros, :cons, length: { maximum: 280 }

  def rating_string
    rating_string = ""
    case self.rating
    when 1
      rating_string = "Like"
    when 0
      rating_string = "Neutral"
    when -1
      rating_string = "Dislike"
    end

    rating_string
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user

  def show
    @note = Note.find(params[:id])
    @house = @note.house
  end

  def new
    @house = House.find(params[:house_id])
    @note = Note.new
  end

  def create
    @house = House.find(params[:house_id])
    @note = @house.notes.build(note_params) # is there a way to include user_id in this?
    @note.user = current_user
    if @note.save
      flash[:notice] = "Note successfully added!"
      redirect_to @house
    else
      render :new
    end
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = "Note successfully updated"
      redirect_to @note
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @house = @note.house
    @note.destroy
    flash[:notice] = "Note successfully deleted"
    redirect_to @house
  end

  private
    def note_params
      params.require(:note).permit(:room, :rating, :pros, :cons)
    end

    # Before filters

    # Confirms a logged-in user
    def logged_in_user
      unless logged_in?
        flash[:notice] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      if !params[:house_id].nil? # check first because only used in new or create
        submitted_user_id = House.find(params[:house_id]).user
      else
        submitted_user_id = Note.find(params[:id]).user
      end
      unless current_user?(submitted_user_id)
        flash[:notice] = "Unauthorized access."
        redirect_to @current_user
      end
    end
end

app/views/notes/_form.html.erb
<%= form_for [@house, @note], html: { class: "note-form" } do |f| %>

  <h4 class="text-center"><%= yield(:form_title) %></h4>

  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@note.errors.count, "error") %> prohibited
        this note from being saved:
      </h2>
      <ul>
        <% @note.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :room, "Room or House Feature" %>
  <%= f.text_field :room %>

  <%= f.label :rating %>
  <%= f.select(:rating, [['Like', 1], ['Neutral', 0], ['Dislike', -1]]) %>

  <%= f.label :pros %>
  <%= f.text_area :pros, placeholder: "Things you like..." %>

  <%= f.label :cons %>
  <%= f.text_area :cons, placeholder: "Things you do not like..." %>

  <div class="expanded button-group">
    <%= f.submit yield(:button_text), class: "success button", id: "note-form-save-button" %>
    <%= link_to "Cancel", yield(:cancel_link), class: "alert button", id: "note-form-cancel-button" %>
  </div>

<% end %>

app/views/notes/edit.html.erb
<% provide(:title, 'Edit Note') %>
<% provide(:form_title, 'Edit Note Form') %>
<% provide(:button_text, 'Update') %>
<% provide(:cancel_link, note_path(@note)) %>

<%= render 'form' %>

app/views/notes/new.html.erb
<% provide(:title, 'New Note') %>
<% provide(:form_title, 'New Note Form') %>
<% provide(:button_text, 'Save') %>
<% provide(:cancel_link, house_path(@house)) %>

<%= render 'form' %>

app/views/notes/show.html.erb
<div class="note-details-top">
  <h1>Note Details</h1>
  <div id="note-details-buttons">
    <div class="small button-group">
      <%= link_to "Back", house_path(@note.house), class: "button" %>
      <%= link_to "Edit", edit_note_path(@note), class: "button success" %>
      <%= link_to "Delete", note_path(@note),  class: "button alert",
                                                            method: :delete, data: { confirm: "Are you sure?" } %>
    </div>
  </div>
</div>

<%= flash[:notice] %>

<div class="note-layout">
  <h3>Notes For <%= @note.room %></h3>
  <h5><span>Rating:</span> <%= @note.rating_string %></h5>
  <h5><span>Pros:</span> <%= @note.pros %></h5>
  <h5><span>Cons:</span> <%= @note.cons %></h5>
</div>