config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  resources :welcome, only: [:index]

  resources :users, except: [:index]

  resources :houses, except: [:index] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, except: [:index, :new, :create]
end

app/views/layouts/_footer.html.erb
<!-- FOOTER SECTION -->
<footer>
  <div class="wrap row small-up-1 medium-up-3">
    <div class="column">
      <h4>Contact Info</h4>
      <hr>
      <a href="#"><span>Phone</span> 234 567 8900</a>
      <a href="#"><span>Email</span> info@company.com</a>
      <a href="#"><span>Address</span> 123 Street Name</a>
    </div>
    <div class="column">
      <h4>Site Map</h4>
      <hr>
      <a href="#">About us</a>
      <a href="#">Contact Us</a>
    </div>
    <div class="column">
      <h4>Social Media</h4>
      <hr>
      <a href="#">Facebook</a>
      <a href="#">Twitter</a>
      <a href="#">Instagram</a>
    </div>
  </div>
</footer>

app/views/layouts/_mobile_menu.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "Sign Up", new_user_path %></li>
  <li><%= link_to "Log In", login_path %></li>
</ul>

app/views/layouts/_navbar.html.erb
<!-- MOBILE NAVIGATION -->

<div class="title-bar show-for-small-only">
  <div class="title-bar-left">
    <button class="menu-icon" type="button" data-open="mobile-menu"></button>
    <span class="title-bar-title">MENU</span>
  </div>
</div>

<!-- DESKTOP NAVIGATION -->

<nav class="top-bar nav-desktop">
  <div class="top-bar-left">
    <h3 class="site-logo">HouseHunter</h3>
  </div>
  <div class="top-bar-right">
    <% if logged_in? %>
      <ul class="menu menu-desktop">
        <li><%= link_to "Home", user_path(current_user) %></li>
        <li><%= link_to "Update", edit_user_path(current_user) %></li>
        <li><%= link_to "Delete", user_path(current_user),  method: :delete,
                                                            data: { confirm: "You sure?" } %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul>
    <% else %>
      <ul class="menu menu-desktop">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) + " | HouseHunter" : "HouseHunter" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <!-- OFF CANVAS MENU -->
    <div class="off-canvas position-left" id="mobile-menu" data-off-canvas>
      <!-- Your menu or Off-canvas content goes here -->
      <%= render 'layouts/mobile_menu' %>
    </div>

    <div class="off-canvas-content" data-off-canvas-content>
      <!-- Your page content lives here -->

      <!-- MOBILE & DESKTOP NAVIGATION -->
      <%= render 'layouts/navbar' %>

      <%= yield %>

      <!-- FOOTER -->
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>